# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.com hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_branch: ""
  autoupdate_commit_msg: "[pre-commit.ci] pre-commit autoupdate"
  autoupdate_schedule: weekly
  skip: []
  submodules: false

repos:
  # General hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
        exclude: \.(md|txt)$
      - id: end-of-file-fixer
        exclude: \.(md|txt)$
      - id: check-yaml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=500"]
      - id: check-case-conflict
      - id: mixed-line-ending
        args: ["--fix=lf"]

  # Flutter/Dart specific hooks
  - repo: local
    hooks:
      - id: dart-format
        name: dart format
        entry: dart format --line-length 100 -o write
        language: system
        files: \.dart$
        pass_filenames: true

      - id: flutter-analyze
        name: flutter analyze
        entry: flutter analyze
        language: system
        files: \.dart$
        pass_filenames: false

      - id: flutter-test
        name: flutter test
        entry: flutter test
        language: system
        files: \.dart$
        pass_filenames: false
        stages: [pre-push] # Only run on push to avoid slowing down commits

  # YAML formatting for config files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types: [yaml]
        exclude: ^(pubspec\.yaml|\.flutter-plugins.*|\.packages)$
        additional_dependencies:
          - prettier@3.3.3
