// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGE4kow9KXmWdJSTiFGmzQAC98-JiQkPY',
    appId: '1:585762962816:web:0ec016f3c57a48a0ba1565',
    messagingSenderId: '585762962816',
    projectId: 'ghar-3c690',
    authDomain: 'ghar-3c690.firebaseapp.com',
    storageBucket: 'ghar-3c690.firebasestorage.app',
    measurementId: 'G-11EFKMK51V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD62dF1_E2tEEMywwD-ZdVPjuPWxvJuDrk',
    appId: '1:585762962816:android:8d1669343bd42cddba1565',
    messagingSenderId: '585762962816',
    projectId: 'ghar-3c690',
    storageBucket: 'ghar-3c690.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOVosaP9qkKwNtI0hUay0VTAPhbFRae4A',
    appId: '1:585762962816:ios:102df6439b133708ba1565',
    messagingSenderId: '585762962816',
    projectId: 'ghar-3c690',
    storageBucket: 'ghar-3c690.firebasestorage.app',
    iosBundleId: 'com.the360ghar.ghar360',
  );
}
