name: Lint & Format

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.35.2'

      - name: Verify Flutter and Dart versions
        run: |
          echo "Flutter version: $(flutter --version)"
          echo "Dart version: $(dart --version)"
          dart_version=$(dart --version 2>&1 | grep -oE '[0-9]+\.[0-9]+\.[0-9]+')
          echo "Dart version extracted: $dart_version"

          if [ -z "$dart_version" ]; then
            echo "❌ Failed to extract Dart version from 'dart --version' output"
            exit 1
          fi

          # Check if Dart version is >= 3.8.0 (matches pubspec.yaml constraint)
          if [ "$(printf '%s\n' "$dart_version" "3.8.0" | sort -V | head -n1)" = "3.8.0" ]; then
            echo "✅ Dart version $dart_version is compatible (≥3.8.0)"
          else
            echo "❌ Dart version $dart_version is incompatible (<3.8.0)"
            exit 1
          fi

      - name: Get dependencies
        run: flutter pub get

      - name: Check formatting
        run: dart format -o none --set-exit-if-changed .

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test --machine --coverage

      - name: Upload coverage to Codecov
        if: github.event_name == 'push'
        uses: codecov/codecov-action@v4
        with:
          file: coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
